---
output:
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction to Git



## What is git?

In technical terms, [git](https://git-scm.com/) is a distributed version control
system that is often used to keep track of software development. In not so 
technical terms, it is a personal archivist/time machine that keeps track of all
the changes you make in a (writing or data analysis) project. Normally, when you
save progress on an analysis, the old version of that analysis is lost. With
git, as you make your steps toward completion of the analysis, you continue to
save your progress, but you also tell git to remember what your analysis looks
like at a certain time by 'committing' to all the changes that have happened.

## Why should I use git?

Git allows you to not only save your work, but to save different versions of
your work through time. Imagine that you were working on writing up an analysis,
but wanted to save a version of your work at the end of the day every day so
that you could go back to it at any time. You would likely have a series of
files that looks like this at the end of three days:

```
audpc_2016-05-25.Rmd
audpc_2016-05-26.Rmd
audpc_2016-05-27.Rmd
```

After three days, it's manageable, but after 20 days, it's difficult to remember
what you did between day 6 and day 7. With git, you only need one file:

```
audpc.Rmd
```

Because you've been recording your progress with git, you not only have access
to all the different versions of your files, but you also have a sensible log of
everything that's been done to the file. Here's what the output of one such `git
log` looks like:

```
commit b8392d0b47528091d4b1a4883d677ed02bdbbe32
Author: Zhian Kamvar <kamvarz@science.oregonstate.edu>
Date:   Wed May 25 14:04:11 2016 -0700

    made figure for publication

commit e3bb7501bf09d597532007b02a8a4fb5bff8ca15
Author: Zhian Kamvar <kamvarz@science.oregonstate.edu>
Date:   Tue May 24 13:41:48 2016 -0700

    calculated audpc

commit 8379234d4c70367dc08d52eabddfc02ef67244fe
Author: Zhian Kamvar <kamvarz@science.oregonstate.edu>
Date:   Mon May 23 13:05:05 2016 -0700

    added field data and packages
```

In this log, you can see three entries on three consecutive days with a message
associated with it (don't worry about the "commit" line, we'll cover that
below). We can see that on Tuesday, data and packages were added, Wednesday, the
AUDPC calculation was performed, and on Thursday, a figure was created.

With git, if a file is deleted or you edited it in a way that makes no sense,
[it's easy to
recover](https://elizabethwickes.com/2016/05/10/how-i-use-github-in-500-words/),
giving you the freedom to try out new things without risk of losing all of your
work.

<!--
- becasuse [branching is cool](http://imgur.com/YG8In8X)
- because [You want to be able to recover your files quickly if they are accidentally deleted](https://elizabethwickes.com/2016/05/10/how-i-use-github-in-500-words/)
- because you want a way to remember your thought process coming up with an analysis
- because you wrote something that makes no sense and just want to go back to a previous version of the project without having to manually delete everything.
-->

# Resources



# Your first repository

## git init

## git add

## git commit

# Conclusions
